site_name: anTraX
site_author: Asaf Gal
copyright: '© 2020'
repo_url: https://github.com/Social-Evolution-and-Behavior/anTraX/
nav:
- Home: index.md
- Installation: installation11.md
- Datasets: datasets.md
- Preparing data for tracking: data_organization.md
- Configuring a tracking session: configuration.md
- Run the tracking: tracking.md
- Classifying tracklets: classification.md
- Graph propagation: propagation.md
- Validating the tracking results: validation.md
- Analyzing tracking results: analysis.md
- Using DeepLabCut to pose-track individuals: dlc.md
- Using JAABA for behavioral classification: jaaba.md
- Using anTraX on HPC environment: hpc.md
- Tips and best practices: tips.md
- Release notes: release.md
theme: readthedocs
markdown_extensions:
    - smarty
    - fenced_code
    - admonition
    - footnotes
    - codehilite:
        guess_lang: true
    - toc:
        permalink: false
plugins:
    - search
